name: Test MsgPack issue

on:
  workflow_dispatch



jobs:
  test_msgpack:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]



    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Test
      run: |
        gem install msgpack
        ruby -e "require 'msgpack'; File.write('repacked2.msgpack', MessagePack.pack([295138067.59645236])); MessagePack.unpack(File.read('repacked2.msgpack'))"
