name: Test bed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | tee github.json
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT" | tee job.json
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT" | tee steps.json
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT" | tee runner.json
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT" | tee strategy.json
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT" | tee matrix.json

      - name: echo toJSON
        env:
            JSON_VALUE: ${{ toJSON(github.event.commits.*.message) }}
        run: echo $JSON_VALUE

      - name: No Skip CI
        if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
        run: echo "No skip-ci entered"

      - name: Skip CI was entered
        if: "contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
        run: echo "skip-ci entered"


      - name: upload github context JSON github.json
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
            name: github contexts
            path: *.json


