name: Test bed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Echo Context
      shell: bash
      run: |
         echo $GITHUB_CONTEXT
